/**
 * 十神 (Ten Gods) computation relative to a day master (日主).
 *
 * Rule: compare element five-phase relation between target stem and day
 * master, then split by yin/yang parity.
 *
 *   same     parity同  → 比肩    parity异  → 劫财
 *   generatedBy parity同  → 偏印  异  → 正印     (target generates DM)
 *   generates  parity同  → 食神   异  → 伤官     (DM generates target)
 *   controlledBy 同 → 七杀  异 → 正官               (target controls DM)
 *   controls   同 → 偏财   异 → 正财                  (DM controls target)
 */

import { STEM_ELEMENT, STEM_YINYANG, type Stem } from './ganzhi';
import { relation } from './wuxing';

export type TenGod =
  | '比肩' | '劫财' | '食神' | '伤官'
  | '偏财' | '正财' | '七杀' | '正官'
  | '偏印' | '正印';

export function tenGodOf(dayMaster: Stem, target: Stem): TenGod {
  const dme = STEM_ELEMENT[dayMaster];
  const te = STEM_ELEMENT[target];
  const sameParity = STEM_YINYANG[dayMaster] === STEM_YINYANG[target];
  const rel = relation(te, dme); // relation of target to DM

  switch (rel) {
    case 'same':
      return sameParity ? '比肩' : '劫财';
    case 'generates': // target generates DM (target → DM)
      return sameParity ? '偏印' : '正印';
    case 'generatedBy': // target generated by DM (DM → target)
      return sameParity ? '食神' : '伤官';
    case 'controls': // target controls DM
      return sameParity ? '七杀' : '正官';
    case 'controlledBy': // target controlled by DM
      return sameParity ? '偏财' : '正财';
  }
}
