/**
 * Build /mnt/documents/ziwei_training.jsonl from src/core/ziwei/external/*.ts.txt
 * Also emits ziwei_corpus.sql with INSERT statements for the RAG table.
 *
 * Usage: bun scripts/build-ziwei-corpus.ts
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync, statSync } from 'fs';
import { join } from 'path';

const ROOT = 'src/core/ziwei/external';
const OUT_JSONL = '/mnt/documents/ziwei_training.jsonl';
const OUT_SQL = '/mnt/documents/ziwei_corpus.sql';

type Entry = {
  source: string;     // file path
  category: string;   // classics | nihai | patterns | sihua | heming
  subcategory?: string;
  title?: string;
  text: string;
  tags?: string[];
};

const entries: Entry[] = [];

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap(f => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const STR = /(?:'([^'\\]*(?:\\.[^'\\]*)*)'|"([^"\\]*(?:\\.[^"\\]*)*)")/g;
function extractStrings(src: string): string[] {
  const out: string[] = [];
  let m: RegExpExecArray | null;
  STR.lastIndex = 0;
  while ((m = STR.exec(src))) {
    const s = (m[1] ?? m[2] ?? '').trim();
    if (s.length >= 6 && /[\u4e00-\u9fff]/.test(s)) out.push(s);
  }
  return out;
}

// Classics: paragraphs use { id: '...', idx: N, text: '...' }
function extractClassics(src: string, file: string) {
  const titleMatch = src.match(/title:\s*'([^']+)'/);
  const bookTitle = titleMatch?.[1] ?? file;
  const para = /text:\s*'([^']+(?:\\.[^']*)*)'/g;
  let m;
  while ((m = para.exec(src))) {
    entries.push({
      source: file,
      category: 'classics',
      subcategory: bookTitle,
      title: bookTitle,
      text: m[1].replace(/\\'/g, "'"),
      tags: [bookTitle],
    });
  }
}

// Patterns: each entry has name + description + source + level
function extractPatterns(src: string, file: string) {
  // greedy match objects with name + description
  const re = /name:\s*'([^']+)'[\s\S]{0,400}?description:\s*'([^']+)'[\s\S]{0,200}?(?:source:\s*'([^']+)')?/g;
  let m;
  while ((m = re.exec(src))) {
    const [, name, desc, source] = m;
    entries.push({
      source: file,
      category: 'patterns',
      subcategory: name,
      title: name,
      text: `【${name}】${desc}${source ? `（出处：${source}）` : ''}`,
      tags: ['格局', name],
    });
  }
}

// Nihai modules: extract name + description + details[] strings
function extractNihai(src: string, file: string) {
  const moduleRe = /\{\s*id:\s*'([^']+)'[\s\S]*?name:\s*'([^']+)'[\s\S]*?description:\s*'([^']+)'/g;
  let m;
  while ((m = moduleRe.exec(src))) {
    entries.push({
      source: file,
      category: 'nihai',
      subcategory: m[2],
      title: m[2],
      text: m[3],
      tags: ['倪海厦', m[2]],
    });
  }
  // chapter content text fields
  const chRe = /title:\s*'([^']+)'[\s\S]{0,300}?description:\s*'([^']+)'/g;
  let c;
  while ((c = chRe.exec(src))) {
    if (c[2].length > 20) {
      entries.push({
        source: file,
        category: 'nihai',
        subcategory: c[1],
        title: c[1],
        text: c[2],
        tags: ['倪海厦'],
      });
    }
  }
}

// Sihua / heming: generic string extraction with file as tag
function extractGeneric(src: string, file: string, category: string) {
  for (const s of extractStrings(src)) {
    if (s.length >= 12) {
      entries.push({ source: file, category, text: s, tags: [category] });
    }
  }
}

const files = walk(ROOT).filter(f => f.endsWith('.ts.txt'));
for (const f of files) {
  const src = readFileSync(f, 'utf8');
  if (f.includes('/classics/data/')) extractClassics(src, f);
  else if (f.endsWith('/patterns.ts.txt')) extractPatterns(src, f);
  else if (f.includes('/nihai/')) extractNihai(src, f);
  else if (f.endsWith('/sihua.ts.txt')) extractGeneric(src, f, 'sihua');
  else if (f.endsWith('/heming-knowledge.ts.txt')) extractGeneric(src, f, 'heming');
}

// Deduplicate by text
const seen = new Set<string>();
const unique = entries.filter(e => {
  const k = e.category + '|' + e.text;
  if (seen.has(k)) return false;
  seen.add(k);
  return true;
});

mkdirSync('/mnt/documents', { recursive: true });

// JSONL — instruction-tuning friendly format
const jsonl = unique.map(e => JSON.stringify({
  instruction: `请用专业的紫微斗数视角，解释以下条目（${e.category}）${e.title ? ` · ${e.title}` : ''}：`,
  input: e.text,
  output: '',  // user to fill / model to learn
  meta: { category: e.category, subcategory: e.subcategory, source: e.source, tags: e.tags },
})).join('\n');
writeFileSync(OUT_JSONL, jsonl);

// SQL — INSERT for ziwei_corpus
const esc = (s: string) => s.replace(/'/g, "''");
const sql = [
  '-- Generated by scripts/build-ziwei-corpus.ts',
  'BEGIN;',
  'TRUNCATE TABLE public.ziwei_corpus;',
  ...unique.map(e =>
    `INSERT INTO public.ziwei_corpus (category, subcategory, title, content, source, tags) VALUES (` +
    `'${esc(e.category)}', ` +
    `${e.subcategory ? `'${esc(e.subcategory)}'` : 'NULL'}, ` +
    `${e.title ? `'${esc(e.title)}'` : 'NULL'}, ` +
    `'${esc(e.text)}', ` +
    `'${esc(e.source)}', ` +
    `ARRAY[${(e.tags ?? []).map(t => `'${esc(t)}'`).join(',')}]::text[]` +
    `);`
  ),
  'COMMIT;',
].join('\n');
writeFileSync(OUT_SQL, sql);

const byCat: Record<string, number> = {};
for (const e of unique) byCat[e.category] = (byCat[e.category] ?? 0) + 1;
console.log(`✓ ${unique.length} entries written to ${OUT_JSONL}`);
console.log(`✓ SQL seed written to ${OUT_SQL}`);
console.log('  by category:', byCat);
