// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.2";

// src/lib/mcp/tools/list-predictions.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-predictions.ts
var list_predictions_default = defineTool({
  name: "list_predictions",
  title: "List saved predictions",
  description: "List the signed-in user's archived prediction runs, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum runs to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("prediction_runs").select("prediction_id, algorithm_version, query_type, final_confidence, generated_at").order("generated_at", { ascending: false }).limit(limit);
    if (error) throw new ToolError(error.message);
    const runs = (data ?? []).map((r) => ({
      predictionId: String(r.prediction_id),
      algorithmVersion: String(r.algorithm_version),
      queryType: String(r.query_type),
      finalConfidence: Number(r.final_confidence),
      generatedAt: String(r.generated_at)
    }));
    return { content: [{ type: "text", text: JSON.stringify(runs) }], structuredContent: { runs } };
  }
});

// src/lib/mcp/tools/get-prediction.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_prediction_default = defineTool2({
  name: "get_prediction",
  title: "Get prediction details",
  description: "Get one archived prediction run (fate vector, engine records, audit blockers) by its prediction ID.",
  inputSchema: { predictionId: z2.string().min(1).describe("Prediction ID from list_predictions.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ predictionId }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("prediction_runs").select("prediction_id, algorithm_version, query_type, final_confidence, generated_at, birth_input, fused_fate_vector, engine_records, audit_blockers").eq("prediction_id", predictionId).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2("Prediction not found");
    return { content: [{ type: "text", text: JSON.stringify(data) }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hlenwvmehbidfpjhbcqu";
var mcp_default = defineMcp({
  name: "iron-plate-oracle",
  title: "Iron Plate Oracle",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in user's archived H-Pulse prediction runs. Use `list_predictions` to browse, then `get_prediction` for details.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_predictions_default, get_prediction_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
