-- Commercial beta privacy hardening.
-- Link all user-owned records to auth.users so account deletion cascades.

ALTER TABLE public.registration_ips
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_registration_ips_user_id
  ON public.registration_ips (user_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'prediction_runs_user_id_fkey'
  ) THEN
    ALTER TABLE public.prediction_runs
      ADD CONSTRAINT prediction_runs_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE NOT VALID;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'prediction_actuals_user_id_fkey'
  ) THEN
    ALTER TABLE public.prediction_actuals
      ADD CONSTRAINT prediction_actuals_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE NOT VALID;
  END IF;
END;
$$;

COMMENT ON COLUMN public.registration_ips.user_id IS
  'Owning auth user; nullable only for legacy records retained for at most 24 hours.';

-- Remove legacy raw IP values from long-lived profiles. New writes are keyed HMAC-like
-- SHA-256 values generated by the edge function; this one-time transform prevents the
-- historical plaintext from remaining visible to administrators.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
UPDATE public.profiles
SET registration_ip = encode(digest(registration_ip, 'sha256'), 'hex')
WHERE registration_ip IS NOT NULL
  AND registration_ip !~ '^[0-9a-f]{64}$';
